#include "stdafx.h"
#include "Vertex.h"

#define VERTEX_DATA D3D11_INPUT_PER_VERTEX_DATA
#define ALIGNED_ELEMENT D3D11_APPEND_ALIGNED_ELEMENT

D3D11_INPUT_ELEMENT_DESC Vertex::Desc[] = 
{
	{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, VERTEX_DATA, 0},
};

D3D11_INPUT_ELEMENT_DESC VertexColor::Desc[] =
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, VERTEX_DATA, 0 },
	{ "COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, ALIGNED_ELEMENT, VERTEX_DATA, 0 },
};

D3D11_INPUT_ELEMENT_DESC VertexTexture::Desc[] =
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, VERTEX_DATA, 0 },
	{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, ALIGNED_ELEMENT, VERTEX_DATA, 0 },
};